services:
    temperatures.access:
        class: DatabaseBundle\TemperaturesAccess
        arguments: [@doctrine.dbal.default_connection]
    users.access:
        class: DatabaseBundle\UsersAccess
        arguments: [@doctrine.dbal.default_connection]