imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DatabaseBundle/Resources/config/services.yml" }
    - { resource: "@WebSocketBundle/Resources/config/services.yml" }
    - { resource: "@WebViewsBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    sm_session_save_path: "%kernel.root_dir%/../var/sessions/"  #%kernel.environment%"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        save_path:   %sm_session_save_path%
        handler_id: session.handler.native_file
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        driver:   pdo_mysql
        host:     localhost
        dbname:   HomeControl
        user:     homecontrol
        password: unicorn
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    connect:
            account_connector: ib_user.oauth_user_provider
    resource_owners:
        facebook:
            type:                facebook
            client_id:           711728598930210
            client_secret:       6ea5effb9d8eb762031b1f1358f98660
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email: email
            options:
                display:         popup
                auth_type:       rerequest
                csrf:            true
        google:
            type:                google
            client_id:           755438172754-bdmrg079mhch5dl2rjsd7n8dlng9tnct.apps.googleusercontent.com
            client_secret:       DNJjhHoF3qcIgjO1eO2XwLh_
            scope:              ""
            paths:
                email: email
            options:
                csrf: true

        github:
            type:                 github
            client_id:           09cd97d3042a640947e7
            client_secret:       437d65347f1fc78f2121a308059e67fc805064f8
            scope:               ""
            paths:
                email: email
            options:
                csrf: true