database:
    resource: "@DatabaseBundle/Controller/"
    type:     annotation
    prefix:   /

web_views:
    resource: "@WebViewsBundle/Controller/"
    type:     annotation
    prefix:   /

rest:
    resource: "@RESTBundle/Controller/"
    type:     annotation
    prefix:   /

web_socket:
    resource: "@WebSocketBundle/Controller/"
    type:     annotation
    prefix:   /


