user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

database:
    resource: "@DatabaseBundle/Controller/"
    type:     annotation
    prefix:   /

web_views:
    resource: "@WebViewsBundle/Controller/"
    type:     annotation
    prefix:   /

web_socket:
    resource: "@WebSocketBundle/Controller/"
    type:     annotation
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

custom_login:
    path: /login/check-custom

github_login:
    path: /login/check-github
