services:
#    web_socket.example:
#        class: WebSocketBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    websocket.command:
        class: WebSocketBundle\Command\ServerCommand
        arguments: [@temperatures.access]