services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    hwi_oauth.user.provider:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    ib_user.oauth_user_provider:
        class: UserBundle\UserProvider
        arguments: [@session, @service_container]